name: CI&&CD

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: build
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      
      - name: Dependent environment
        run: |
          npm i -g @angular/cli
          npm i
      
      - name: Compile
        run: |
          npm run build
      
      - name: Deploy
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SECRET }}
          uploads: |
            dist/web-ble => ${{ secrets.DEPLOY_DIR }}
